### ISSUE TITLE
Training data preprocess

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#10]
Hi! 
I run the training code and It told me that 
"FileNotFoundError: [Errno 2] No such file or directory: './data/eccv2020_MGCNet_data/train.txt'"

I do not know how to generate the "train.txt". 
Could you please share the codes to generate the "train.txt" for the four datasets? (300W-LP, Multi-PIE, CelebA, LS3D)
Thank you very much, haha!

**Comment by jiaxiangshang** [comment]
Hi Haokun,
1. If you download the training dataset demo, you can found the 'train.txt file, maybe you need to change the PATH.
2. To generate the training data
(1) We list all the related methods and data.
(2) In the test file, we give all the preprocessing steps
(3) It is easy to define a tensorflow dataloader as you like, define yourselves's train,txt
For processing code, they are a mess and include many libs of my colleague, and we do not have a plan to release this part code.
