### ISSUE TITLE
Why there is a "ssim loss" in the loss funtion?

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#11]
Hi!
Good morning! I read the code of "build_graph.py" and found that there is a "ssim loss" in the loss funtion of MGCNet. However, I can not find the related description of "ssim loss" in the ECCV paper. 
Maybe "ssim loss" is an additional loss? 
![image](https://user-images.githubusercontent.com/34161960/93658753-00ce7400-fa71-11ea-9b46-6aef7fd84f65.png)

**Comment by jiaxiangshang** [comment]
That is a attempt，but I fail. 
So, for the final result, I set the ssim loss weight as 0.0.

Maybe you can show us how to benefit form ssim in your work.
