### ISSUE TITLE
Preprocess on CelebA

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#12]
Hi! Good morning!
As we can see in the demo data, you selected three images from the same identity to generate the training samples.
（1）I want to know the strategy that you used to select images. Are you just randomly select three images from the same identity?
（2）What's more,the CelebA dataset provides the ground truth landmarks. To construct the xxxx_cam.txt, I need the landmark position of all these three images. Should I use the ground truth landmarks from CelebA dataset, or use the predicted landmarks from "face_alignment" detector. I think we should use the predicted landmarks because the ECCV paper shows that "The images are automatically annotated by the 2D landmark detection method in [8] and the face detection method in [65]"?
(3) Thanks for your answer very much!

![image](https://user-images.githubusercontent.com/34161960/93841003-d96fe500-fcc4-11ea-8dd7-fdb407c1e8f2.png)

**Comment by jiaxiangshang** [comment]
(1) Yes, randomly select
(2) celebA have 5 landmark, but we need 68 lm, so the landmark detector is always needed.
