### ISSUE TITLE
Preprocess on LS3D-W

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#13]
Hi! I download the LS3D-W dataset and face some problems. Could you please give me some advise? Thanks very much！
(1)  As we can see in the demo dataset, you concat three images from one identity to generate the training sample. Should I always concat three images from one identity to generate the training sample? Or I can contact three images from different identity?
![image](https://user-images.githubusercontent.com/34161960/93979601-254b8880-fdb0-11ea-80f5-4ac2d47dd5f5.png)

(2）When I preprocessing the CelebA and 300W-LP datasets, I can get the identity information from the "identity_CelebA.txt" or  the name of images.  However, when I preprocess the LS3D-W dataset, I have no way to get the identity information of the images. Therefor, how do you generate the training samples for each identity with three images in LS3D-W dataset? Especially for the "300W-Testset-3D", "AFLW2000-3D-Reannotated", and "Menpo-3D" folder in LS3D-W dataset?
![image](https://user-images.githubusercontent.com/34161960/93979683-3e543980-fdb0-11ea-8116-cd4643e2ac4b.png)

**Comment by jiaxiangshang** [comment]
Firstly, your download data seems different from mine, and I change my computer that I can not see my data now.
(1) In my memory, the LS3d-w have data that only one image for one identity, so the concat image can from different datasets.
(2) These problems won't affect training obviously, just concat as your like.

**Comment by HaoKun-Li** [comment]
Thanks for your comments.
I acquired the LS3D-W dataset from the [official paper page ](https://www.adrianbulat.com/face-alignment), and I received two kinds of datasets, [the original dataset](https://uniofnottm-my.sharepoint.com/:u:/g/personal/adrian_bulat_nottingham_ac_uk/EfIp7E0s2-JAtgvxdNauPUQB7XTVwEOpR9tT_ohiwDNUWw?e=TDg9Qu) and [the balanced subset](https://www.adrianbulat.com/downloads/FaceAlignment/LS3D-W-balanced-20-03-2017.zip ), respectively.  I use the original dataset previously and show the architecture above.

Maybe you have used the balanced subset? Now, I am downloading the balanced subset. I will show the architecture of this subset later.  
![image](https://user-images.githubusercontent.com/34161960/94008547-c6006f00-fdd5-11ea-97ac-89ce1d01711b.png)

**Comment by jiaxiangshang** [comment]
Yes, my teammates use this.
