### ISSUE TITLE
Run test_image.py GPU memory error

### ISSUE THREAD

**Issue by fuxiongcs** [jiaxiangshang/MGCNet#17]
when I run test_image.py,there is an error as follow:

![error](https://user-images.githubusercontent.com/15098590/95722915-1ff2a700-0ca7-11eb-83c9-b71b40cff119.png)

How much gpu memory is needed for this project？

Thank you! 

GPU info:
`
GTX2080,  GPU Memory 8G
`

**Comment by jiaxiangshang** [comment]
emm.....
The code can be run on 1080, 2070, 2080 such 8G memory card, so have you check the current GPU memory with nvidia-smi.
And the batch_size = 1 default, have you change this?

**Comment by fuxiongcs** [comment]
Thank you for your reply！
I did not change the code and the batch_size = 1. I check the current GPU memory with nvidia-smi, the result is as follow:
Before the program runs：
![2020-10-12 17-39-39屏幕截图](https://user-images.githubusercontent.com/15098590/95731904-a82a7980-0cb2-11eb-9de5-e2b533c431ef.png)
After the program runs，I took a picture before the program crashed：
![2020-10-12 17-39-13屏幕截图](https://user-images.githubusercontent.com/15098590/95732127-fa6b9a80-0cb2-11eb-9183-ecf136829ccd.png)

The memory seems to be insufficient.

**Comment by jiaxiangshang** [comment]
Emm.. If only for testing, I recommend the CPU mode, now I use a 2060 6G card which also has GPU memory problem.
So I use CPU mode, it performs a good test speed.

**Comment by fuxiongcs** [comment]
OK，thanks！
