### ISSUE TITLE
Question about the initial value of the pose variables

### ISSUE THREAD

**Issue by fuxiongcs** [jiaxiangshang/MGCNet#18]
Hi:
I have read your source code, there is three variables about pose,defined_pose_main,defined_pose_left and defined_pose_right. Could you tell me how their initial value was calculated？ If I want to test with my own data, how should I set the initial value？thanks！
![2020-10-13 17-27-18屏幕截图](https://user-images.githubusercontent.com/15098590/95845109-5a7a4380-0d7c-11eb-9a9a-48334daaed52.png)
![2020-10-13 17-27-29屏幕截图](https://user-images.githubusercontent.com/15098590/95845769-2eab8d80-0d7d-11eb-9129-5a136302fdb4.png)

**Comment by jiaxiangshang** [comment]
Yes man, thanks for reading my code carefully:)
The main pose is defined by myself, and you can define yourself.

I provide the code in MGCNet/src_common/geometry/face_align/generate_align_self.py
This will show you how to define the main pose. After a busy time, I may clean such code to tools, but now............

Thanks for using our work, hhhhhh~
