### ISSUE TITLE
Question about the "Average and standard deviation" of RMSE on MICC Florence

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#19]
Hi! 
I notice that only the table 1(b) provides the  "Average and standard deviation" of metrics. 
I want to know how to get the "Average and standard deviation". I think there are two ways：
（1）Train the MGCNet many times, and evaluate every MGCNet to get the average and standard deviation of RMSE.
（2）MICC has 53 people. So we can calculate the average RMSE of all 53 people and the standard deviation of them.

Could you tell me which way is used in your paper? Thanks very much.

![image](https://user-images.githubusercontent.com/34161960/95971018-39c8f100-0e43-11eb-83a2-8712c0116efd.png)

**Comment by jiaxiangshang** [comment]
We do this like (2), average all people.
