### ISSUE TITLE
How to organize the data of multi view datasets?

### ISSUE THREAD

**Issue by deepmo24** [jiaxiangshang/MGCNet#20]
Hi, for 300W-LP and Multi-PIE datasets, the face images of a person have different yaw angles i.e. [0°, 90°] for 300W-LP and [-90°, 90°] for Multi-PIE. 
1.  how to select three view images to construct a data item? for example, the angle are less than a threshold. 
2. there are several compositions of the same person with different angles, what's the strategy you used to select data of one person? how many data you construct for one person?

**Comment by jiaxiangshang** [comment]
I do not use angle > 90, which is a common constrain about 'extreme pose'.
The three view needs proper overlap, I just use neighbor.

' how many data you construct for one person?' I do not understand this, further detail?
:+1:

**Comment by deepmo24** [comment]
For example, there are 20 images of a person with different angles. how many triples(three images with different angles) can I generate? I mean having 20 images of a person,  there are many combinations of three images to choose from.

**Comment by jiaxiangshang** [comment]
Yes,
How to pick camera pose related image
(1) we cut the extreme pose, then we cut the two transpose camera.
(2) then for the near camera(we only pick one from two/three).
You can see the mpie paper, they give camera aerial view, we totally sample 7 images, using different picking strategy won't have a large difference,

**Comment by deepmo24** [comment]
ok, thanks a lot.
