### ISSUE TITLE
How can I get the skin file of image?

### ISSUE THREAD

**Issue by GGOSinon** [jiaxiangshang/MGCNet#22]
I'm trying to use a custom dataset to train the model using train_unsupervised.py.

However, it seems that it needs a skin image (named as ..._skin.jpg).

How can I get those skin images from plain images?

**Comment by jiaxiangshang** [comment]
Skin classification / segmentation algorithm. Or ask help from deng yu.

**Comment by GGOSinon** [comment]
Ahh I got it. Thank you for the fast response!

**Comment by chenbolinstudent** [comment]
@GGOSinon 
How do you  get the skin file of image?

**Comment by GGOSinon** [comment]
I used the skin detector from WillBrennan's github. (https://github.com/WillBrennan/SkinDetector/blob/master/skin_detector/skin_detector.py)

**Comment by chenbolinstudent** [comment]
I'm trying to use a custom dataset to train the model using train_unsupervised.py.

where is the  custom dataset  ? can you share it? 
and how to use the<https://github.com/WillBrennan/SkinDetector/blob/master/skin_detector/skin_detector.py> to train the dataset in detail?

**Comment by GGOSinon** [comment]
I am using FaceScape dataset (https://facescape.nju.edu.cn). 

I used the process() function of skin_detector to generate the skin image.

You could make a skin image from source image as the below code snippet:
```
image_bgr = src_img
image_rgb = image_bgr[..., ::-1]
lm_trans, img_warped, tform = crop_align_affine_transform(lm_howfar, image_rgb, FLAGS.img_height, std_224_bfm09)
skin = skin_detector.process(img_warped[...,::-1])
```

**Comment by jiaxiangshang** [comment]
Thanks for your sharing, I will learn it either. hhhh~
