### ISSUE TITLE
bazel build problem

### ISSUE THREAD

**Issue by lelechen63** [jiaxiangshang/MGCNet#23]
Thanks for your excellent work. I am trying to show some comparison with you. But I am stucked at installing mesh_rendering step... Have you seen this problem beofre?
![image](https://user-images.githubusercontent.com/24720604/97190736-79190b00-177c-11eb-82eb-62270a860fd1.png)

**Comment by lelechen63** [comment]
solved with the tf_mesh_renderer provided by you! Thanks, it would be great if you can point out that we should use MGCNet/thirdParty/tf_mesh_renderer instead of the original github.

**Comment by jiaxiangshang** [comment]
Thanks for your nice words and suggestions.

**Comment by zyf2316** [comment]
> solved with the tf_mesh_renderer provided by you! Thanks, it would be great if you can point out that we should use MGCNet/thirdParty/tf_mesh_renderer instead of the original github.

I encountered the same problem. How could you solve it? And I used the MGCNet/thirdParty/tf_mesh_renderer. Is it related to bazel on NFS?
