### ISSUE TITLE
Question about the filter of training sample

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#24]
Hello!
I notice that you say in the paper that:

> "We filter the face pose, face attribution, low-resolution images, and blurred images  and obtain ∼390K face images"

I want to know more detail about the filter procedure. For example, how do you filter images according to face attribution and face pose? And how do you judge the blurred images? Because I generate about 420K samples but some samples are outliers, such as:
![image](https://user-images.githubusercontent.com/34161960/97516937-3307b580-19cf-11eb-8068-cf69805d9efb.png)

Thanks for your reply very much!

**Comment by jiaxiangshang** [comment]
' filter the face pose, face attribution, low-resolution images, and blurred images'  is mainly work on celebA
celebA's gt has the attribution about glass and blur, such images are discarded.

For face pose, you can refer to previous issue, how we cut mpie.

low-resolution cut is a common sense.
