### ISSUE TITLE
Any ideas to improve the performers of eye close face images?

### ISSUE THREAD

**Issue by CodingMice** [jiaxiangshang/MGCNet#25]
I found that the output result of model is half close eye when input is a full close eye image.

**Comment by jiaxiangshang** [comment]
Actually, the eye close is mainly benefited from the landmark loss, and eye close training data.
However, the eye close training image is not enough, that why the eye close prediction is not perfect.

**Comment by CodingMice** [comment]
> Actually, the eye close is mainly benefited from the landmark loss, and eye close training data.
> However, the eye close training image is not enough, that why the eye close prediction is not perfect.

Thanks for your answer. BTW, is it possible to generate data by using closed eye RGB data?

**Comment by jiaxiangshang** [comment]
emm.... 
(1) maybe GAN generate method
(2) geometry based methods are difficult to do this, the only one is alfw3d dataset
