### ISSUE TITLE
About eval on BU-3DFE

### ISSUE THREAD

**Issue by hao-qiang** [jiaxiangshang/MGCNet#26]
Hi, 

1. In your paper, before eval on BU-3DFE dataset, a dense correspondence map should be pre-computed first, which method should I use to compute this map.
2. Which data should I use, F3D.wrl or RAW.wrl?
3. Are input images F2D.bmp, or rendered by F3D.wrl.

Thanks!

**Comment by jiaxiangshang** [comment]
Hi, haoqiang

From our paper, you will find that this eval method comes from Tewari's excellent method "FML"

And such eval data also comes from him.

You may need to ask for help from him.

Jiaxiang

**Comment by hao-qiang** [comment]
Thanks.
