### ISSUE TITLE
Questions about the pose and projection matrix in the code

### ISSUE THREAD

**Issue by deepmo24** [jiaxiangshang/MGCNet#29]
Hi, sorry to disturb you. I have several questions about the pose and projection matrix code.

**1. why we need to add defined_pose_main to pred_pose_render?**
![image](https://user-images.githubusercontent.com/19352002/99510923-95e2e000-29c2-11eb-91ca-b31540cf4738.png)

**2. what do the variables "list_gpmm_mv" and "list_gpmm_eye" do ? I found they are calculated from rotation matrix and translation vector, and used in [mesh_renderer_camera_light()](https://github.com/jiaxiangshang/MGCNet/blob/254b74515d280e430559eba3229183bd55099052/src_common/geometry/render/api_tf_mesh_render.py#L18), but I don't know the meaning of them.**
![image](https://user-images.githubusercontent.com/19352002/99515046-68e4fc00-29c7-11eb-8793-d997f55cf638.png)

**3. [in project3d_batch()](https://github.com/jiaxiangshang/MGCNet/blob/254b74515d280e430559eba3229183bd55099052/src_common/geometry/camera_distribute/camera_utils.py#L94), why the projected landmarks need to be divided by  'pt_batch_homo_2d_w'**
![image](https://user-images.githubusercontent.com/19352002/99514619-e9efc380-29c6-11eb-9443-c7d7b0122955.png)

**Comment by jiaxiangshang** [comment]
The basic questions, I suggest you ask your advisior.

**Comment by deepmo24** [comment]
Yes, these are actually basic questions hhhhh... I will figure them out. Thanks.

**Comment by jiaxiangshang** [comment]
For the first question, this has an insight that gives a main_pose can help the network convergence fast, it just like give a good init value.

**Comment by deepmo24** [comment]
thank you so much.
