### ISSUE TITLE
Could you please provide the paper link

### ISSUE THREAD

**Issue by ForrestPi** [jiaxiangshang/MGCNet#3]
Excellent Work! but I cannot find the paper.  Could you please provide the paper link

**Comment by jiaxiangshang** [comment]
Thanks for your nice words.
I have submitted the paper to arxiv for preprint, the email shows that it will be announced on 2020.07.28. I will update the link as soon as possible.

**Comment by jiaxiangshang** [comment]
Now the paper link is given.
