### ISSUE TITLE
Self-adjoint eigen decomposition was not successful.

### ISSUE THREAD

**Issue by miaoYuanyuan** [jiaxiangshang/MGCNet#30]
when I use facenet as perception loss , this error happen: from align.py :line 110, in TransformFromPointsTF : tf.self_adjoint_eig(N)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Self-adjoint eighen decomposition was not successful , the input might not be valid.
[[{node SelfAdjointEigV2}]]
[[{{node gradients/Reshape_37_grad/Shape}}]]. my tf.version is 1.13.0

when I swith tf 1.13.1. there are another problem:
InvalidArgumentError :Got info = 3 for batch index  0 , expected info=0, debug_info = heevd

I can't found any solution for this problem .can you help me ? Thank you !

**Comment by jiaxiangshang** [comment]
Have your change the code for your task?

**Comment by miaoYuanyuan** [comment]
> Have your change the code for your task?

I use the facenet-align part in your code for my work , and change nothing,  and the error happens randomly, may the first iter in training, or my the any time in training.

**Comment by jiaxiangshang** [comment]
Ok, I have face the same problems.
I find that the reason is because of the bad init.
When the network starts training, the 3dmm or pose is bad, then 2d landmark is bad.
So, the alignment will face an invalid similarity transform, so -> bug happen.
I can not give further suggestions, but I think you now know how to debug.

**Comment by miaoYuanyuan** [comment]
Thank you for your reply. 
I know your means, but I have no idea to solve it, I try to catch  this exception ,but I failed , because I don't know  when the error will happend, how to reproduce this error ,and fix it.   if it always happens , traning process will can't continue ... can you give me some advices ?  Thank you !

**Comment by jiaxiangshang** [comment]
The problem comes from the lm2d, if the init lm2d is always valid, the problem will be solved.
In my code, I predict camera pose with a main pose, then the lm2d will be good, this op solves the problem.
For your project, I think u can get the predicted lm2d to be good, and this will be solved.

**Comment by miaoYuanyuan** [comment]
Thank you , your solution is valid. I also use the main pose in my project , it will not tenimal . but perhaps i should change a appropriate main pose or change render code  . I will check my project and read your code carefully. Thank you very much !

**Comment by jiaxiangshang** [comment]
Good news, thanks for using our work.
