### ISSUE TITLE
Test on video

### ISSUE THREAD

**Issue by sstzal** [jiaxiangshang/MGCNet#32]
Hi. The "test_image.py" is used to inference a single unprocessed image. And I have a question: **How to inference on a video directly?**  Since I want to get more frame consistency. If I inference these frames individually, there may have some jitter, and I want to know how to address this problem?

**Comment by jiaxiangshang** [comment]
Maybe the multi-view methods can help you, their inference phase benefit from frame consistency.

**Comment by sstzal** [comment]
> Maybe the multi-view methods can help you, their inference phase benefit from frame consistency.

So can I take multi-view images as input when inference in this repo?

**Comment by jiaxiangshang** [comment]
MGCNet is the monocular method, maybe the multi-view methods can help.

**Comment by sstzal** [comment]
> MGCNet is the monocular method, maybe the multi-view methods can help.

Thanks!
