### ISSUE TITLE
Colab demo plz...

### ISSUE THREAD

**Issue by mumumu99** [jiaxiangshang/MGCNet#34]
Dear @jiaxiangshang,
Thank you for you great work.

I don't know how to set the environment.
So I want you to write it so that you can practice with colab.
Is it possible?

**Comment by jiaxiangshang** [comment]
Hi, mumumu99

The colab can set the environment as linux, you can follow our environment steps in the readme.

Currently, we won't support other platforms.

**Comment by cuizhanyuan** [comment]
I wrote a colab demo.@[mumumu99](https://github.com/mumumu99)
[https://colab.research.google.com/drive/1G8aQFFXp5a3-9x4RbraOuEo7TaA6WPRh?usp=sharing](https://github.com/jiaxiangshang/MGCNet/issues/url)

**Comment by zyf2316** [comment]
> I wrote a colab demo.@[mumumu99](https://github.com/mumumu99) [https://colab.research.google.com/drive/1G8aQFFXp5a3-9x4RbraOuEo7TaA6WPRh?usp=sharing](https://github.com/jiaxiangshang/MGCNet/issues/url)

When I run it, it can not bazel completely. Could you check for the problem? I tried different vesion of tensorflow and numpy, but there are still some errors.
