### ISSUE TITLE
More Question about the evaluation of 3D face reconstruction

### ISSUE THREAD

**Issue by heyoon01** [jiaxiangshang/MGCNet#35]
Hi Thanks for sharing your work! 
Really appreciate it!
I went through the issues in #16 but still have some questions.

When you use the MICC dataset video, which frames did you use?
I watched the video, and found that it contains frames that don't capture the whole face cause it's too zoomed in.
I think the face detection in this case would fail and not be able to generate any reconstruction.
So then I wonder which frames you used.

Did you not need to specify them because you have the testing code of all other works that you compared with,
and ran them with the same frames?

Thanks!

**Comment by jiaxiangshang** [comment]
Thanks for using our work!

For the MICC dataset video, we follow Trans's method mentioned in our paper.

For your question, we sure jump the frame which fails in face detection.

For testing code, I get the **_averaged_** result from them(I do not need the same frames), and I reproduce their number by my colleague's eval code, then we compare.

I think cutting the face detection fail frames is a commonly accepted operation(personal, hhh~)

**Comment by heyoon01** [comment]
Thank you for your fast and kind response!
