### ISSUE TITLE
Is the provided pretrained weight, not from a model trained on MultiPIE dataset?

### ISSUE THREAD

**Issue by heyoon01** [jiaxiangshang/MGCNet#37]
Hi!

I'm doing a personal project on top of your work with the provided pretrained weights
and I really thank you for sharing your work.

I have tested test_image.py on an image from MultiPIE dataset,
and the results are sometimes good, but sometimes bad.
Here's a bad example.
![image](https://user-images.githubusercontent.com/43199166/119254046-193df200-bbef-11eb-8f59-42cd26942274.png)

Results of left and right images are generally good, but this problem is often observed for frontal images.
I was wondering if the pretrained weights are not from a model that was trained with MultiPIE dataset.

I am planning to fine-tune the weights with MultiPIE dataset, but just needed to check if this would help. 

Thank you.

**Comment by jiaxiangshang** [comment]
Hi man, sorry for the late reply.

The MGCNet is trained with M-PIE, for the in the front images and large pose images of M-PIE, I always use large pose images as this is helpful for our multi-view geometry consistency. I guess that this is the problem, if you planning to fine-tune, only M-PIE will give bad result, as in-the-wild images is very important.

**Comment by heyoon01** [comment]
Thank you for your reply.

Why are images with large poses better for using multi-view geometry consistency?
Isn't baseline what matters? I mean the baseline between the triple images.

Also I don't get why this gives me poor results on MPIE when it's good at in-the-wild images.
This problem actually occurs a bit often for frontal images on MPIE,,,

Thanks!

**Comment by jiaxiangshang** [comment]
Picking the large pose samples, do not affect the baseline for enough overlap, you can see the MPIE camera distribution.

For training, mgcnet does not see many front Mpie faces, so the result is bad, this is a common machine learning understanding, right?

**Comment by heyoon01** [comment]
Actually I was wondering why the large poses are _better_.
I mentioned baseline because I thought only having too large baseline can
harm the training with multi-view losses.
What are the advantages of training with large pose images with respect to multiview losses?

Thank you for the reply.

**Comment by jiaxiangshang** [comment]
Picking... views, get proper baseline.

I do not know "training with large pose images" or "training with front images" is better////

**Comment by heyoon01** [comment]
Oh alright, I thought by saying
"I always use large pose images as this is helpful for our multi-view geometry consistency" in your first reply,
you meant that it is better for training. Maybe I misunderstood.
Thanks for the reply. It was a great help.

**Comment by jiaxiangshang** [comment]
Oh, my fault.

But it is sure my init idea, as large pose case is mostly benefit from multi-view geometry consistency.

In this way, I pick images as I like............, the result is I do not know if the problem happens here,
