### ISSUE TITLE
ImportError: cannot import name 'rasterize_triangles' from 'thirdParty.tf_mesh_renderer.mesh_renderer.rasterize_triangles' 

### ISSUE THREAD

**Issue by JudyCodes321** [jiaxiangshang/MGCNet#39]
I use "pip install mesh_renderer" instead of compile tf_mesh_renderer from github. But I meet this, "ImportError: cannot import name 'rasterize_triangles' from 'thirdParty.tf_mesh_renderer.mesh_renderer.rasterize_triangles' "
But there isn't a function named "rasterize_triangles" in rasterize_triangles.py.

**Comment by jiaxiangshang** [comment]
Read the readme file, this module needs compile by ourselves.
