### ISSUE TITLE
NameError: name 'rasterize_triangles' is not defined

### ISSUE THREAD

**Issue by JudyCodes321** [jiaxiangshang/MGCNet#40]
File "/home/wjj/MGCNet/src_common/geometry/render/api_tf_mesh_render.py", line 97，uses function "rasterize_triangles".
But tf_mesh_renderer/mesh_renderer/rasterize_triangles.py does not have 
"def rasterize_triangles() ", only has rasterize(). 
When I rename "rasterize()" to rasterize_triangles() in 
 tf_mesh_renderer/mesh_renderer/rasterize_triangles.py, there's an error  in the last function parameter (,[-1] * vertex_attributes.shape[2].value), "TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn."
Does anyone meet this issue?

**Comment by jiaxiangshang** [comment]
Which version of tf_mesh_render u are using.

**Comment by JudyCodes321** [comment]
I used this version, "https://github.com/google/tf_mesh_renderer". I replace it with yours, and I have solved this problem. Thanks!
