### ISSUE TITLE
compile tf_mesh_renderer

### ISSUE THREAD

**Issue by yjnanan** [jiaxiangshang/MGCNet#41]
When I use bazel to compile tf_mesh_renderer, I met the problem shown in the following:
MGCNet-master/thirdParty/tf_mesh_renderer/mesh_renderer/kernels/BUILD:8:8: Executing genrule //mesh_renderer/kernels:rasterize_triangles_kernel failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

**Comment by jiaxiangshang** [comment]
Are you sure that you follow each cmd provided by us?
