### ISSUE TITLE
What does the first parameter '0'/  '1' (in train.txt ) mean? I notice different samples have different multi-view loss weight ,because of this parameter.

### ISSUE THREAD

**Issue by JudyCodes321** [jiaxiangshang/MGCNet#42]
I am trying a different multi-view face dataset. But I don't know how to set this parameter . It seems that the value of this parameter is higher,'2', when the input three images have similar lighting environment. I am not very clear about this. Could you tell me how to set this parameter? @jiaxiangshang ,thanks !

**Comment by jiaxiangshang** [comment]
Not all multi-view face data is suitable for multi-view losses, '0' is monocular and "2" is the most suitable one.

**Comment by JudyCodes321** [comment]
I understand. Thanks!
