### ISSUE TITLE
Why are pictures and texts(landmarks, intrinsics ) organized in a different order?

### ISSUE THREAD

**Issue by JudyCodes321** [jiaxiangshang/MGCNet#45]
Faces and skin images are in order (source1,target,source2), but landmarks and intrinsics are read in order (target,source1,source2). I am confused about this. Could you tell me why do this? I think it's easy to make mistakes here.
  Besides, there is "defined_pose_main" in " build_train_graph". If training on a new dataset, do I need to reset this parameter?
@jiaxiangshang

**Comment by jiaxiangshang** [comment]
In the further process, one of them is aligned as same order with another, maybe you have not read such code.

This part sure make people confused, you can modify this IO code to a better version.

**Comment by JudyCodes321** [comment]
Thank you for your reply. Indeed,I don't use process code provided.
In build_graph.py, function set_constant_node set "defined_pose_main"= tf.constant([0.000000, 0.000000, 3.141593, 0.17440447, 9.1053238, 4994.3359], shape=[1, 6]).
Could you tell me if it's necessary to reset the parameter "defined_pose_main" when training on a new dataset? 
![Snipaste_2021-08-04_08-50-50](https://user-images.githubusercontent.com/46815856/128104820-7a078186-c3d1-45a0-b4b9-d0c3d9303301.png)

**Comment by jiaxiangshang** [comment]
Yes, as predicting camera pose is diffcult, we provide a init for training.
