### ISSUE TITLE
bazel build problem

### ISSUE THREAD

**Issue by hao-qiang** [jiaxiangshang/MGCNet#5]
I use bazel=0.10.0 and gcc=7.5 to build mesh_renderer, but can not generate rasterize_trangles_kernel.so. thanks
![image](https://user-images.githubusercontent.com/28535732/91020867-979c4200-e625-11ea-93e4-9b83e6f9326a.png)

**Comment by jiaxiangshang** [comment]
Hi, hao

you can find the *.so in ./tf_mesh_render/bazel-out folder

**Comment by hao-qiang** [comment]
thanks, I find generate rasterize_trangles_kernel.so in 'tf_mesh_render/bazel-out/k8-fastbuild/genfiles/mesh_render/kernels/' and copy it into 'tf_mesh_render/mesh_render/kernels', but find another error:
![image](https://user-images.githubusercontent.com/28535732/91042914-279db400-e645-11ea-83ba-f726a392ae4d.png)

**Comment by jiaxiangshang** [comment]
It because that so tensorflow lib can not found, you need check the BUILD file, the compile cmd depends on your system.

**Comment by ForrestPi** [comment]
@hao-qiang  find the BUILD file  change -D_GLIBCXX_USE_CXX11_ABI=0  to -D_GLIBCXX_USE_CXX11_ABI=1     it helps for me
