### ISSUE TITLE
How fast does your model render a face?

### ISSUE THREAD

**Issue by sunshinewhy** [jiaxiangshang/MGCNet#50]
I use some pre-trained 3DMM models to reconstruct face image, but the speed of model is too low, I want to know how much time your model need to render a face image, thanks!

**Comment by jiaxiangshang** [comment]
< 1s

**Comment by sunshinewhy** [comment]
@jiaxiangshang Can you tell me the configuration of your device (e.g. the cpu and gpu, Linux/Windows)? I wanna try it. Thanks!

**Comment by jiaxiangshang** [comment]
gpu, 1080TI, ubuntu 16.04
14 batch_size in training need 1s, included rendering
