### ISSUE TITLE
Questions about pose of dataset

### ISSUE THREAD

**Issue by yjhong89** [jiaxiangshang/MGCNet#52]
Hi. Thanks for great work!

I have few questsions of dataset.
1. Is there any other dataset for training rather than 'Multi-Pie' and '300W-LP'?
2. How get ground-truth pose data (camera extrinsic, rotation/translation) for '300W-LP' datasets? Isn't it wild images ?
  - I have not downloaded 'Multi-Pie' dataset, but I think this dataset might have gt pose data

Thank you.

Best regards,
YJHong.

**Comment by jiaxiangshang** [comment]
For Q1: Facescape dataset, multi-view dataset is expensive and indoor setting
For Q2: We do not use the gt pose, we predict pose and leveraging multi-view geometry consistency.
I do not think so, they have not

**Comment by yjhong89** [comment]
@jiaxiangshang 
Thanks for replying.

For Q2, then how predict pose vector (rotation, translation) ? Is there any code reference that you would recommend ?

**Comment by jiaxiangshang** [comment]
the mgcnet predict the pose actually, you can also see DECA, Deep3DFace......

**Comment by yjhong89** [comment]
@jiaxiangshang 
Thank you. 

These are things that I understand so far.
- We need rotation/translation/depth information to leverage multiview-geometry consistency.
- Since ground-truth rotation/translation/depth information doesn't exist for 300W-LP, and MPIE, estimated pose vectors from 3dmm module (DECA, MGCNET, Deep3DFace) are used for multiview-geometry  ? (below Equation)
  ![image](https://user-images.githubusercontent.com/26890721/165915916-4b2cac0c-7f10-4d7d-bd48-361a221d5924.png)

**Comment by jiaxiangshang** [comment]
Yes, that is the main idea of MGCNet... :)

**Comment by yjhong89** [comment]
@jiaxiangshang Thank you! It is very clear!
