### ISSUE TITLE
bazel build problem

### ISSUE THREAD

**Issue by HaoKun-Li** [jiaxiangshang/MGCNet#7]
First, I use 'conda install bazel==0.11.1' to install bazel 0.11.1. I use the default gcc of ubuntu 18.04.2 is 7.5.0. However, when I run 'Bazel build ...', I got these error:
![image](https://user-images.githubusercontent.com/34161960/92397049-aa9c2f80-f158-11ea-863d-0f644913385c.png)
 It seems that the bazel can not get the gcc file?

Then, I try to use 'conda install gcc==4.8.5' to install gcc 4.8.5. But after I install gcc 4.8.5, I can not import tensorflow. Here are the errors:
![image](https://user-images.githubusercontent.com/34161960/92399369-cacded80-f15c-11ea-9844-a11a7adf47eb.png)

I really want to know how to install the bazel and gcc? Maybe I should not use conda to install them? Thanks for you help!

**Comment by jiaxiangshang** [comment]
It is introduced in the readme.md like bazel==10.1, gcc==5.*

If you want to using gcc=4.*, you need to try these two settings, which is used to include old version gcc.
-D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1

**Comment by HaoKun-Li** [comment]
> It is introduced in the readme.md like bazel==10.1, gcc==5.*
> 
> If you want to using gcc=4.*, you need to try these two settings, which is used to include old version gcc.
> -D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1

Thanks. We use the binary installer to install bazel 0.10.1 and use the default gcc 7.5.0 of ubuntu 18.04. And I use PyTorch 0.4.1 rather than torch 0.4.0 for some reason. Now I can run the test_image.py successfully!
![Uploading image.png…]()

**Comment by RishengDeng** [comment]
> > It is introduced in the readme.md like bazel==10.1, gcc==5.*
> > If you want to using gcc=4.*, you need to try these two settings, which is used to include old version gcc.
> > -D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1
> 
> Thanks. We use the binary installer to install bazel 0.10.1(do not use conda to install bazel) and use the default gcc 7.5.0 of ubuntu 18.04(do not use conda to install gcc, too) . And I use PyTorch 0.4.1 rather than torch 0.4.0 for some reason(if I use torch 0.4.0, there will be some error). Now I can run the test_image.py successfully!
> ![image](https://user-images.githubusercontent.com/34161960/92477763-bf89c900-f213-11ea-95fd-29f0edc0c52f.png)

Hello, could you please tell me more specifically about your environment?
I also use the binary installer to install bazel 0.10.1 and use the default gcc 7.50 of ubuntu 18.04, however, I cannot build the tf_mesh_renderer. Do you download the tf_mesh_renderer repository from  this repository or from the origin? And what is the code you run to build the rendder, just 'bazel test ...' or some other? It confuses me, if you can reply that will be very nice.

**Comment by jiaxiangshang** [comment]
> > > It is introduced in the readme.md like bazel==10.1, gcc==5.*
> > > If you want to using gcc=4.*, you need to try these two settings, which is used to include old version gcc.
> > > -D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1
> > 
> > 
> > Thanks. We use the binary installer to install bazel 0.10.1(do not use conda to install bazel) and use the default gcc 7.5.0 of ubuntu 18.04(do not use conda to install gcc, too) . And I use PyTorch 0.4.1 rather than torch 0.4.0 for some reason(if I use torch 0.4.0, there will be some error). Now I can run the test_image.py successfully!
> > ![image](https://user-images.githubusercontent.com/34161960/92477763-bf89c900-f213-11ea-95fd-29f0edc0c52f.png)
> 
> Hello, could you please tell me more specifically about your environment?
> I also use the binary installer to install bazel 0.10.1 and use the default gcc 7.50 of ubuntu 18.04, however, I cannot build the tf_mesh_renderer. Do you download the tf_mesh_renderer repository from this repository or from the origin? And what is the code you run to build the render, just 'bazel test ...' or some other? It confuses me if you can reply that will be very nice.

Hi risheng,
Thank you for using our work.
Firstly, we use tensorflow rather than pytorch.
Secondly, the bazel version and gcc version, and the tf_mesh_render are clear in the README.md.
We make changes with tf_mesh_render, so git clone --recursive https://github.com/jiaxiangshang/MGCNet.git.
The git cmd needs this.
Further, gcc version larger the 5.* is not friendly for tf_mesh_render.

**Comment by HaoKun-Li** [comment]
> > > It is introduced in the readme.md like bazel==10.1, gcc==5.*
> > > If you want to using gcc=4.*, you need to try these two settings, which is used to include old version gcc.
> > > -D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1
> > 
> > 
> > Thanks. We use the binary installer to install bazel 0.10.1(do not use conda to install bazel) and use the default gcc 7.5.0 of ubuntu 18.04(do not use conda to install gcc, too) . And I use PyTorch 0.4.1 rather than torch 0.4.0 for some reason(if I use torch 0.4.0, there will be some error). Now I can run the test_image.py successfully!
> > ![image](https://user-images.githubusercontent.com/34161960/92477763-bf89c900-f213-11ea-95fd-29f0edc0c52f.png)
> 
> Hello, could you please tell me more specifically about your environment?
> I also use the binary installer to install bazel 0.10.1 and use the default gcc 7.50 of ubuntu 18.04, however, I cannot build the tf_mesh_renderer. Do you download the tf_mesh_renderer repository from this repository or from the origin? And what is the code you run to build the rendder, just 'bazel test ...' or some other? It confuses me, if you can reply that will be very nice.

First, I change my path to the root of the ./third_part/tf_mesh/render by cd xxxxxxxxx. Then, I use this command to bulid the tf render:
bazel build ...
